const data = {
  users: [
    {
      name: "Leo",
      email: "leosolari9@gmail.com",
      password: "123456",
      isAdmin: true,
    },
    {
      name: "Pepito",
      email: "asd@asd.com",
      password: "123456",
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: "1",
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      // _id: "2",
      name: "Adidas fit shirt",
      slug: "adidas-fit-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 5,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 12,
      description: "High quality products",
    },
    {
      // _id: "3",
      name: "Nike Slim pants",
      slug: "nike-slim-pants",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "High quality Pant",
    },
    {
      // _id: "4",
      name: "Adidas fit pants",
      slug: "adidas-fit-pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 2,
      brand: "Puma",
      rating: 4.4,
      numReviews: 17,
      description: "Top tier pants",
    },
    {
      // _id: "5",
      name: "Adidas shoes",
      slug: "adidas-shoes",
      category: "Shoes",
      image: "/images/p5.jpg",
      price: 35,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 4,
      description: "High quality shoe",
    },
    {
      // _id: "6",
      name: "Nike shoes",
      slug: "nike-shoes",
      category: "Shoes",
      image: "/images/p6.jpg",
      price: 40,
      countInStock: 0,
      brand: "Nike",
      rating: 4.7,
      numReviews: 12,
      description: "High quality shoes",
    },
    {
      //  _id: "7",
      name: "Versace cap",
      slug: "versace-cap",
      category: "Caps",
      image: "/images/p7.jpg",
      price: 2500,
      countInStock: 2,
      brand: "Versace",
      rating: 3.5,
      numReviews: 4,
      description: "Nice hat",
    },
    {
      //  _id: "8",
      name: "World Cup ball",
      slug: "world-cup-ball",
      category: "Balls",
      image: "/images/p8.jpg",
      price: 550,
      countInStock: 1,
      brand: "Adidas",
      rating: 4.9,
      numReviews: 45,
      description: "World Cup Ball",
    },
    {
      //  _id: "9",
      name: "Gucci flip flops",
      slug: "gucci-flip-flops",
      category: "Shoes",
      image: "/images/p9.jpg",
      price: 100,
      countInStock: 0,
      brand: "Gucci",
      rating: 2.7,
      numReviews: 0,
      description: "Gucci flip flops - bhad baddie",
    },
    {
      //  _id: "10",
      name: "Lacoste sweater",
      slug: "lacoste-sweater",
      category: "Sweater",
      image: "/images/p10.jpg",
      price: 50,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 6,
      description: "Nice sweater",
    },
    {
      //  _id: "11",
      name: "Sarkany shoes",
      slug: "sarkany-shoes",
      category: "Shoes",
      image: "/images/p11.jpg",
      price: 230,
      countInStock: 4,
      brand: "Sarkany",
      rating: 3.6,
      numReviews: 4,
      description: "Sarkany shoes",
    },
    {
      // _id: "12",
      name: "Reebok sneakers",
      slug: "reebok-shoes",
      category: "Shoes",
      image: "/images/p12.jpg",
      price: 33,
      countInStock: 12,
      brand: "Reebok",
      rating: 3.7,
      numReviews: 7,
      description: "Reebok sneakers",
    },
  ],
};

export default data;
